version: "3.9"

volumes:
  postgres-data:
  static-data:
  media-data:

services:
  djangoapp:
    user: duser
    container_name: djangoapp
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./djangoapp:/djangoapp
      # - ./data/web/static:/data/web/static/
      # - ./data/web/media:/data/web/media/
      - static-data:/data/web/static
      - media-data:/data/web/media
    env_file:
      - ./dotenv_files/.env
    depends_on:
      - psql
  psql:
    container_name: psql
    image: postgres:13-alpine
    volumes:
      # - ./data/postgres/data:/var/lib/postgresql/data/
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./dotenv_files/.env
    ports:
      - 5432:5432
