# Generated by Django 4.2.6 on 2023-10-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stacks_choices', models.CharField(choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA')], default='PYTHON', max_length=10)),
            ],
        ),
    ]
