# Generated by Django 4.2.7 on 2023-11-19 23:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('squads', '0004_alter_usersonsquads_squad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StackOnSquad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='squads.squad')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stacks.stack')),
            ],
        ),
        migrations.AddField(
            model_name='stack',
            name='squads',
            field=models.ManyToManyField(related_name='stacks', through='stacks.StackOnSquad', to='squads.squad'),
        ),
        migrations.AddConstraint(
            model_name='stackonsquad',
            constraint=models.UniqueConstraint(fields=('stack', 'squad'), name='stack_on_squad_unique'),
        ),
    ]
