# Generated by Django 4.2.6 on 2023-10-20 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stacks',
            old_name='stacks_choices',
            new_name='stack',
        ),
    ]
