# Generated by Django 4.2.6 on 2023-10-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stacks',
            name='nome',
        ),
        migrations.AddField(
            model_name='stacks',
            name='escolha',
            field=models.CharField(choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA')], default='DEFAULT VALUE', max_length=30),
        ),
        migrations.AlterField(
            model_name='stacks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
