# Generated by Django 4.2.6 on 2023-10-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0002_remove_stacks_nome_stacks_escolha_alter_stacks_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stacks',
            name='escolha',
            field=models.CharField(choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA'), ('JAVASCRIPT', 'JAVASCRIPT'), ('PHP', 'PHP'), ('RUBY ON RAILS', 'RUBY ON RAILS'), ('UX/UI', 'UX/UI'), ('DEVOPS', 'DEVOPS'), ('BIG DATA', 'BIG DATA'), ('C#/.NET', 'C#/.NET'), ('FLUTTER', 'FLUTTER'), ('RUST', 'RUST'), ('ANDROID', 'ANDROID'), ('IOS', 'IOS'), ('CLOUD (AWS/AZURE)', 'CLOUD (AWS/AZURE)'), ('IA', 'IA')], default='DEFAULT VALUE', max_length=30),
        ),
    ]
