# Generated by Django 4.2.6 on 2023-10-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0003_categorias_stack_delete_stacks'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='stacks',
            field=models.CharField(choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA')], default='PYTHON', max_length=10),
        ),
        migrations.DeleteModel(
            name='Stack',
        ),
    ]
