# Generated by Django 4.2.6 on 2023-10-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0003_alter_stacks_escolha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stacks',
            old_name='escolha',
            new_name='nome',
        ),
    ]
