# Generated by Django 4.2.6 on 2023-10-21 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0004_categorias_stacks_delete_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stack', to='stacks.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
