# Generated by Django 4.2.6 on 2023-10-26 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0004_rename_escolha_stacks_nome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stacks',
            old_name='nome',
            new_name='name',
        ),
    ]
