# Generated by Django 4.2.6 on 2023-10-21 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0005_categoria_stack_delete_categorias'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='choice',
            field=models.CharField(choices=[('PYTHON', 'PYTHON'), ('JAVA', 'JAVA')], default='PYTHON', max_length=20),
        ),
    ]
