# Generated by Django 4.2.6 on 2023-10-24 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0009_stacks_remove_ordered_customer_delete_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stacks',
            old_name='stack',
            new_name='name',
        ),
    ]
