# Generated by Django 4.2.6 on 2023-10-24 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0010_rename_stack_stacks_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stacks',
            old_name='name',
            new_name='nome',
        ),
    ]
