# Generated by Django 4.2.6 on 2023-10-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0011_rename_name_stacks_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stacks',
            name='id',
        ),
        migrations.AlterField(
            model_name='stacks',
            name='choice_stacks',
            field=models.CharField(choices=[('DEFAULT', 'DEFAUT'), ('PYTHON', 'PYTHON'), ('JAVA', 'JAVA')], default='DEFAULT', max_length=30),
        ),
        migrations.AlterField(
            model_name='stacks',
            name='nome',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
