# Generated by Django 4.2.6 on 2023-10-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0012_remove_stacks_id_alter_stacks_choice_stacks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stacks',
            name='nome',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
