# Generated by Django 4.2.6 on 2023-10-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0013_alter_stacks_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stacks',
            new_name='Stack',
        ),
    ]
