# Generated by Django 4.2.6 on 2023-10-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0014_rename_stacks_stack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='stack',
            name='pessoas',
            field=models.ManyToManyField(to='stacks.pessoas'),
        ),
    ]
