# Generated by Django 4.2.6 on 2023-10-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0015_pessoas_stack_pessoas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoas',
            new_name='Participantes',
        ),
        migrations.AlterField(
            model_name='stack',
            name='pessoas',
            field=models.ManyToManyField(blank=True, to='stacks.pessoas'),
        ),
    ]
