# Generated by Django 4.2.6 on 2023-10-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0016_rename_pessoas_participantes_alter_stack_pessoas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantes',
            name='nome',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='stack',
            name='pessoas',
            field=models.ManyToManyField(blank=True, to='stacks.participantes'),
        ),
    ]
