# Generated by Django 4.2.6 on 2023-10-25 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0017_alter_participantes_nome_alter_stack_pessoas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='pessoas',
        ),
        migrations.DeleteModel(
            name='Participantes',
        ),
    ]
