# Generated by Django 4.2.6 on 2023-10-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0017_alter_participantes_nome_alter_stack_pessoas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='choice_stacks',
        ),
        migrations.RemoveField(
            model_name='stack',
            name='pessoas',
        ),
        migrations.AddField(
            model_name='stack',
            name='id',
            field=models.AutoField(default='DEFAULT', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stack',
            name='nome',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Participantes',
        ),
    ]
