# Generated by Django 4.2.6 on 2023-10-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0018_remove_stack_pessoas_delete_participantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stack',
            name='choice_stacks',
        ),
        migrations.AddField(
            model_name='stack',
            name='id',
            field=models.AutoField(default='DEFAULT', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stack',
            name='nome',
            field=models.CharField(max_length=30),
        ),
    ]
