# Generated by Django 4.2.6 on 2023-10-25 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stacks', '0018_remove_stack_choice_stacks_remove_stack_pessoas_and_more'),
        ('stacks', '0019_remove_stack_choice_stacks_stack_id_alter_stack_nome'),
    ]

    operations = [
    ]
