# Generated by Django 4.2.6 on 2023-10-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersonsquads',
            options={'verbose_name_plural': 'Squad'},
        ),
    ]
