# Generated by Django 4.2.6 on 2023-10-22 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0002_alter_usersonsquads_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersonsquads',
            options={'verbose_name_plural': 'Squads'},
        ),
    ]
