# Generated by Django 4.2.6 on 2023-10-22 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('squads', '0003_alter_usersonsquads_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersonsquads',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_on_squad', to='squads.squad'),
        ),
    ]
